task/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home_page, name='index'),
    path('add_project', add_project, name='add_project'),   
    path('add_task', add_task, name='add_task'),
    path('add_activity', add_activity, name='add_activity'),    
    path('project_list', project_list, name='project_list'),
]

task_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),    
]

task/models.py
from django.db import models
from .choice import *

class Project(models.Model):
    project_name = models.CharField(max_length=255)
    project_owner = models.CharField(max_length=255, null=True, blank=True)
    project_location = models.CharField(max_length=255, null=True, blank=True)
    project_type = models.CharField(max_length=255, null=True, blank=True)
    project_start = models.DateField(null=True, blank=True)
    project_end = models.DateField(null=True, blank=True)
    project_user = models.CharField(max_length=255, null=True, blank=True)
    priority = models.CharField(max_length=255, default='LOW', choices=CHOICE_PRIORITY)
    description = models.TextField(null=True, blank=True)
    deadline = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=255, default='IN-PROCESS', choices=CHOICE_PROJECT_STATUS)

    def __str__(self):
        return self.project_name

class Task(models.Model):
    task_name = models.CharField(max_length=255)
    task_owner = models.CharField(max_length=255, null=True, blank=True)
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
    task_start = models.DateField(null=True, blank=True)
    task_end = models.DateField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=255, default='IN-PROCESS', choices=CHOICE_TASK_STATUS)

    def __str__(self):
        return self.task_name

class Activity(models.Model):
    task_id = models.ForeignKey(Task, on_delete=models.CASCADE)
    # activity_name = models.CharField(max_length=255)
    activity_owner = models.CharField(max_length=255, null=True, blank=True)
    activity_start = models.DateField(null=True, blank=True)
    activity_end = models.DateField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=255, default='IN-PROCESS', choices=CHOICE_TASK_STATUS)

    def __str__(self):
        return self.description

task/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['required'] = 'true'

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['required'] = 'true'

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ActivityForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['required'] = 'true'

task/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import *
from .models import *

def home_page(request):
    context = {
        'obj_project': Project.objects.all(),
        'obj_task': Task.objects.all(),
        'obj_activity': Activity.objects.all(),
    }
    return render(request, 'home.html', context)

def add_project(request):
    context = {
        'form': ProjectForm(),
    }
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            context['form'] = form
            context['message'] = "Data has been saved !!!"
            return render(request, 'add_project.html', context)
        else:
            context['form'] = form
            context['message'] = "Please enter valid data."
            return render(request, 'add_project.html', context)            
    return render(request, 'add_project.html', context)

def project_list(request):
    context = {
        'obj_project': Project.objects.all(),
    }           
    return render(request, 'project_list.html', context)

def add_task(request):
    context = {
        'form': TaskForm(),
    }
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            context['form'] = form
            context['message'] = "Data has been saved !!!"
            return render(request, 'add_task.html', context)
        else:
            context['form'] = form
            context['message'] = "Please enter valid data."
            return render(request, 'add_task.html', context)            
    return render(request, 'add_task.html', context)

def add_activity(request):
    context = {
        'form': ActivityForm(),
    }
    if request.method == 'POST':
        form = ActivityForm(request.POST)
        if form.is_valid():
            form.save()
            context['form'] = form
            context['message'] = "Data has been saved !!!"
            return render(request, 'add_activity.html', context)
        else:
            print(form.errors)
            context['form'] = form
            context['message'] = "Please enter valid data."
            return render(request, 'add_activity.html', context)            
    return render(request, 'add_activity.html', context)

task/templates/add_activity.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form method="POST" action="{% url 'add_activity' %}" autocomplete="off">
    {% csrf_token %}
            <center><strong>{{message}}</strong> </center>
            <hr class="my-2">
            <h3> ADD NEW ACTIVITY </h3>
                <hr class="my-2">
    <div class="row">
            <div class="col-md-6">
                    <div class="form-group">
                        <label for="">Task Name</label>
                        {{form.task_id}}
                    </div>
                </div>
                <div class="col-md-3">
                        <div class="form-group">
                            <label for="">Status</label>
                            {{form.status}}
                        </div>
                    </div>                  
    </div>
<div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label for="">Start Date</label>
                {{form.activity_start}}
                <small id="" class="form-text text-muted">Date Format: mm/dd/yyyy</small>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="">End Date</label>
                {{form.activity_end}}
                <small id="" class="form-text text-muted">Date Format: mm/dd/yyyy</small>
            </div>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="form-group">
                <label for="">Description</label>
                <textarea class="form-control" id="id_description" name="description"
                    rows="3">{{form.description.value}}</textarea>
                <small id="help_id_description" class="form-text text-muted">Please enter task activity</small>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">ADD ACTIVITY</button>
</form>
{% endblock %}

task/templates/add_project.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form method="POST" action="{% url 'add_project' %}" autocomplete="off">
    {% csrf_token %}
            <center><strong>{{message}}</strong> </center>
            <hr class="my-2">
            <h3> ADD NEW PROJECT </h3>
                <hr class="my-2">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="">Project Name</label>
                {{form.project_name}}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="">Project Owner</label>
                {{form.project_owner}}
            </div>
        </div>
        <!-- <div class="col-md-3">
                <div class="form-group">
                    <label for="">Type</label>
                    {{form.project_type}}
                </div>
        </div> -->
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label for="">Start Date</label>
                {{form.project_start}}
                <small id="" class="form-text text-muted">Date Format: mm/dd/yyyy</small>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="">End Date</label>
                {{form.project_end}}
                <small id="" class="form-text text-muted">Date Format: mm/dd/yyyy</small>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="">Location</label>
                {{form.project_location}}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label for="">Priority</label>
                {{form.priority}}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="">Deadline Date</label>
                {{form.deadline}}
                <small id="" class="form-text text-muted">Date Format: mm/dd/yyyy</small>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="">Status</label>
                {{form.status}}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="form-group">
                <label for="">Description</label>
                <textarea class="form-control" id="id_description" name="description"
                    rows="3">{{form.description.value}}</textarea>
                <small id="help_id_description" class="form-text text-muted">Please enter project description</small>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">ADD PROJECT</button>
</form>

{% endblock %}

task/templates/add_task.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form method="POST" action="{% url 'add_task' %}" autocomplete="off">
    {% csrf_token %}
            <center><strong>{{message}}</strong> </center>
            <hr class="my-2">
            <h3> ADD NEW TASK </h3>
                <hr class="my-2">
    <div class="row">
        <div class="col-md-9">
            <div class="form-group">
                <label for="">Task Name</label>
                {{form.task_name}}
            </div>
        </div>
    </div>
    <div class="row">
            <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Task Owner</label>
                        {{form.task_owner}}
                    </div>
                </div>
                <div class="col-md-3">
                        <div class="form-group">
                            <label for="">Project Name</label>
                            {{form.project_id}}
                        </div>
                    </div>        
                    <div class="col-md-3">
                            <div class="form-group">
                                <label for="">Status</label>
                                {{form.status}}
                            </div>
                        </div>  
    </div>
<div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label for="">Start Date</label>
                {{form.task_start}}
                <small id="" class="form-text text-muted">Date Format: mm/dd/yyyy</small>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="">End Date</label>
                {{form.task_end}}
                <small id="" class="form-text text-muted">Date Format: mm/dd/yyyy</small>
            </div>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="form-group">
                <label for="">Description</label>
                <textarea class="form-control" id="id_description" name="description"
                    rows="3">{{form.description.value}}</textarea>
                <small id="help_id_description" class="form-text text-muted">Please enter task description</small>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">ADD TASK</button>
</form>
{% endblock %}

task/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="card">
<div class="test-scroll" style="position:relative;">
    <div class="card-body p-b-0">
        <div class="review-block">
            {% for project in obj_project %}
            <div class="card">
            <div class="card-body">
            <div class="row">
                <div class="col">
                    <h6 class="m-b-10">Project: {{project.project_name}}</h6>
                    <div class="row align-items-center">
                        <div class="col">
                            <div class="progress">
                                <div class="progress-bar bg-c-green" style="width:85%"></div>
                            </div>
                        </div>
                        <div class="col">
                            <h6 class="text-muted float-right f-12">{{project.status}}</h6>
                        </div>
                    </div>
                    <table class="table table-hover m-4">
                        <thead>
                            <tr>
                                <th class="text-muted">TASK NAME</th>
                                <th class="text-muted">OWNER</th>
                                <th class="text-muted">CREATED</th>
                                <th class="text-muted">STATUS</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for task in obj_task %}
                            {% if project.project_name == task.project_id.project_name %}
                            <tr>
                                <td>
                                    <h6 class="mb-1">{{task.task_name}}</h6>
                                    <!-- <p class="m-0"></p> -->
                                </td>
                                <td>
                                    <!-- <p class="mb-1">523.423</p> -->
                                    <span class="text-c-green m-0">{{task.task_owner}}</span>
                                </td>
                                <td>{{task.task_start}}</td>
                                <td><a class="badge badge-primary f-12" href="#!">{{task.status}}</a></td>
                            </tr> 
                            {% else %}
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                    <!-- <p class="m-t-10 m-b-0">Hello</p> -->
                </div>
            </div>
            </div>
            </div>
    
            {% endfor %}
        </div>
    </div>
</div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            // [ test-scroll ] start
            var px = new PerfectScrollbar('.test-scroll', {
                wheelSpeed: .5,
                swipeEasing: 0,
                wheelPropagation: 1,
                minScrollbarLength: 40,
            });
            // [ text-scroll ] end
        });
    });
</script>

{% endblock %}

task/templates/home2.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="card-body">
    <div class="latest-update-box">
        <div class="row p-b-30">
            <div class="col-auto text-right update-meta">
                <i class="feather icon-check f-w-600 bg-c-green update-icon"></i>
            </div>
            <div class="col p-l-5">
                <a href="#!">
                    <h6 class="m-0">New Order Received.</h6>
                </a>
                <p class="m-b-0">Hemilton</p>
            </div>
        </div>
        <div class="row p-b-30">
            <div class="col-auto text-right update-meta">
                <i class="feather icon-briefcase bg-c-red update-icon"></i>
            </div>
            <div class="col p-l-5">
                <a href="#!">
                    <h6 class="m-0">You have 3 pending Task.</h6>
                </a>
                <p class="m-b-0">Hemilton</p>
            </div>
        </div>
        <div class="row p-b-30">
            <div class="col-auto text-right update-meta">
                <i class="feather icon-check f-w-600 bg-c-green update-icon"></i>
            </div>
            <div class="col p-l-5">
                <a href="#!">
                    <h6 class="m-0">New Order Received.</h6>
                </a>
                <p class="m-b-0">Shirley Hoe</p>
            </div>
        </div>
        <div class="row">
            <div class="col-auto text-right update-meta">
                <i class="feather icon-briefcase bg-c-red update-icon"></i>
            </div>
            <div class="col p-l-5">
                <a href="#!">
                    <h6 class="m-0">You have 2 pending Task.</h6>
                </a>
                <p class="m-b-0">James Alexander</p>
            </div>
        </div>
    </div>
</div>
</div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            // [ new-scroll ] start
            var px = new PerfectScrollbar('.new-scroll', {
                wheelSpeed: .5,
                swipeEasing: 0,
                wheelPropagation: 1,
                minScrollbarLength: 40,
            });
            // [ new-scroll ] end
        });
    });
</script>
    <script>
        feather.replace()
      </script>
{% endblock %}

task/templates/project_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        <div class="table-responsive">
        <div class="full-scroll" style="height:375px;position:relative;">
        <table class="table table-hover">
        <thead>
        <tr>
        <th>Project Name</th>
        <th>Owner</th>
        <th>Start Date</th>
        <th>Deadline Date</th>
        <th>Status</th>
        <th class="text-right">Priority</th>
        </tr></thead>
        <tbody>
            {% for project in obj_project %}
                <tr>
                <td>{{project.project_name}}</td>
                <td>{{project.project_owner}}</td>
                <td>{{project.project_start}}</td>
                <td>{{project.deadline}}</td>
                <td><a href="#!" class="badge badge-primary">{{project.status}}</a></td>
                <td class="text-right">{{project.priority}}</td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
        </div>
        </div>
        <script type="text/javascript">
                                $(document).ready(function() {
                                    $(function() {
                                        // [ full-scroll ] start
                                        var px = new PerfectScrollbar('.full-scroll', {
                                            wheelSpeed: .5,
                                            swipeEasing: 0,
                                            wheelPropagation: 1,
                                            minScrollbarLength: 40,
                                        });
                                        // [ full-scroll ] end
                                    });
                                });
                            </script>

{% endblock %}